name: Log4Minecraft
version: '${project.version}'
main: wtf.melonthedev.log4minecraft.Main
api-version: 1.19
authors: [ Melonthedev ]
description: A customizable logger for minecraft with console logging - logging to a textfile - logging to a file which can be inspected and viewed with several commands - inventory backup system

commands:
  logoutput:
    description: Set the loglevel of a certain output [Team Only]
  logaction:
    description: Set the actions that should be logged [Team Only]
  playeractivity:
    description: Detect suspicious playeractivity [Team Only]
    aliases:
      - checksusplayeractivity
  findevent:
    description: Find a log entry [Team Only]
    aliases:
      - findlog
      - searchlog
  logcategory:
    description: Sets a category for specific items and mobs [Team Only]
  manageinventory:
    description: Manages inventories, creates and restores backups [Team Only]